-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 00:25:51 2024
-- Model: New Model    Version: 1.0

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb`;

-- -----------------------------------------------------
-- Table `mydb`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROLES` (
  `codigo_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45)  NULL,
  PRIMARY KEY (`codigo_rol`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `codigo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombres_user` VARCHAR(45) NOT NULL,
  `last_name_user` VARCHAR(45) NOT NULL,
  `cedula_user` VARCHAR(45) NOT NULL UNIQUE,
  `correo_user` VARCHAR(45) NOT NULL UNIQUE,
  `codigo_rol` INT NOT NULL,
  `pass_user` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`codigo_usuario`),
  CONSTRAINT `fk_codigo_rol`
    FOREIGN KEY (`codigo_rol`)
    REFERENCES `ROLES` (`codigo_rol`)
   
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`TIPO_DE_VEHICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TIPO_DE_VEHICULO` (
  `tipo_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `nombre_vehiculo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo_vehiculo`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`VEHICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VEHICULO` (
  `placa_vehiculo` VARCHAR(45) NOT NULL,
  `tipo_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`placa_vehiculo`),
  CONSTRAINT `fk_tipo_vehiculo`
    FOREIGN KEY (`tipo_vehiculo`)
    REFERENCES `TIPO_DE_VEHICULO` (`tipo_vehiculo`)
   
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`ASOCIADO_VEHICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASOCIADO_VEHICULO` (
  `codigo_asociado_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `codigo_usuario` INT NOT NULL,
  `placa_vehiculo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_asociado_vehiculo`),
  CONSTRAINT `fk_usuario_asociado_vehiculo`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `USUARIOS` (`codigo_usuario`)
   ,
  CONSTRAINT `fk_placa_vehiculo_asociado_vehiculo`
    FOREIGN KEY (`placa_vehiculo`)
    REFERENCES `VEHICULO` (`placa_vehiculo`)
   
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`INGRESO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INGRESO` (
  `codigo_ingreso` INT NOT NULL,
  `codigo_usuario` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `hora_entrada_ingreso` DATETIME(6) NOT NULL,
  `hora_salida_ingreso` DATETIME(6) NOT NULL,
  PRIMARY KEY (`codigo_ingreso`),
  CONSTRAINT `fk_codigo_usuario_ingreso`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `USUARIOS` (`codigo_usuario`)
   
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`COMPUTADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMPUTADOR` (
  `serial_computador` VARCHAR(45) NOT NULL,
  `nombre_computador` VARCHAR(45) NOT NULL,
  `marca_computador` VARCHAR(45) NOT NULL,
  `color_computador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`serial_computador`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`INGRESO_ELEMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INGRESO_ELEMENTOS` (
  `codigo_ingreso` INT NOT NULL,
  `codigo_elementos` VARCHAR(45) NOT NULL,
  `tipo_elemento` ENUM('COMPUTADOR', 'VEHICULO') NOT NULL,
  PRIMARY KEY (`codigo_ingreso`, `codigo_elementos`),
  CONSTRAINT `fk_codigo_ingreso_elementos`
    FOREIGN KEY (`codigo_ingreso`)
    REFERENCES `INGRESO` (`codigo_ingreso`)
   
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`ASOCIADO_COMPUTADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ASOCIADO_COMPUTADOR` (
  `codigo_asociado_computador` INT NOT NULL,
  `codigo_usuario` INT NOT NULL,
  `serial_computador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_asociado_computador`),
  CONSTRAINT `fk_codigo_usuario_asociado_computador`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `USUARIOS` (`codigo_usuario`)
   ,
  CONSTRAINT `fk_serial_computador_asociado_computador`
    FOREIGN KEY (`serial_computador`)
    REFERENCES `COMPUTADOR` (`serial_computador`)
   
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
