-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 00:25:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROLES` (
  `codigo_rol` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_rol`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`CARGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CARGO` (
  `codigo_cargo` INT NOT NULL,
  `nombre_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_cargo`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `codigo_usuario` INT NOT NULL,
  `nombres_user` VARCHAR(45) NOT NULL,
  `last_name_user` VARCHAR(45) NOT NULL,
  `cedula_user` VARCHAR(45) NOT NULL,
  `correo_user` VARCHAR(45) NOT NULL,
  `cargo_user` INT NOT NULL,
  `codigo_rol` INT NOT NULL,
  `pass_user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_usuario`),
  CONSTRAINT `fk_codigo_rol`
    FOREIGN KEY (`codigo_rol`)
    REFERENCES `mydb`.`ROLES` (`codigo_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargo_usuario`
    FOREIGN KEY (`cargo_user`)
    REFERENCES `mydb`.`CARGO` (`codigo_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`TIPO DE VEHICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO DE VEHICULO` (
  `tipo_vehiculo` INT NOT NULL,
  `nombre_vehiculo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo_vehiculo`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`VEHICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VEHICULO` (
  `placa_vehiculo` VARCHAR(45) NOT NULL,
  `tipo_vehiculo` INT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`placa_vehiculo`),
  CONSTRAINT `fk_tipo_vehiculo`
    FOREIGN KEY (`tipo_vehiculo`)
    REFERENCES `mydb`.`TIPO DE VEHICULO` (`tipo_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`ASOCIADO_VEHICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASOCIADO_VEHICULO` (
  `codigo_asociado_vehiculo` INT NOT NULL,
  `codigo_usuario` INT NOT NULL,
  `placa_vehiculo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_asociado_vehiculo`),
  CONSTRAINT `fk_usuario_asociado_vehiculo`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `mydb`.`USUARIOS` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_placa_vehiculo_asociado_vehiculo`
    FOREIGN KEY (`placa_vehiculo`)
    REFERENCES `mydb`.`VEHICULO` (`placa_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`INGRESO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INGRESO` (
  `codigo_ingreso` INT NOT NULL,
  `codigo_usuario` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `hora_entrada_ingreso` DATETIME(6) NOT NULL,
  `hora_salida_ingreso` DATETIME(6) NOT NULL,
  PRIMARY KEY (`codigo_ingreso`),
  CONSTRAINT `fk_codigo_usuario_ingreso`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `mydb`.`USUARIOS` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`COMPUTADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMPUTADOR` (
  `serial_computador` VARCHAR(45) NOT NULL,
  `nombre_computador` VARCHAR(45) NOT NULL,
  `marca_computador` VARCHAR(45) NOT NULL,
  `color_computador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`serial_computador`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`INGRESO_ELEMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INGRESO_ELEMENTOS` (
  `codigo_ingreso` INT NOT NULL,
  `codigo_elementos` VARCHAR(45) NOT NULL,
  `tipo_elemento` ENUM('COMPUTADOR', 'VEHICULO') NOT NULL,
  CONSTRAINT `fk_codigo_ingreso_elementos`
    FOREIGN KEY (`codigo_ingreso`)
    REFERENCES `mydb`.`INGRESO` (`codigo_ingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codigo_elementos_computador`
    FOREIGN KEY (`codigo_elementos`)
    REFERENCES `mydb`.`COMPUTADOR` (`serial_computador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codigo_elementos_vehiculo`
    FOREIGN KEY (`codigo_elementos`)
    REFERENCES `mydb`.`VEHICULO` (`placa_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`ASOCIADO_COMPUTADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASOCIADO_COMPUTADOR` (
  `codigo_asociado_computador` INT NOT NULL,
  `codigo_usuario` INT NOT NULL,
  `serial_computador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_asociado_computador`),
  CONSTRAINT `fk_codigo_usuario_asociado_computador`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `mydb`.`USUARIOS` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serial_computador_asociado_computador`
    FOREIGN KEY (`serial_computador`)
    REFERENCES `mydb`.`COMPUTADOR` (`serial_computador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
